ALTER TABLE BOOKS ADD BESTSELLER BOOLEAN;

SELECT * FROM BOOKS;
SELECT * FROM RENTS;
SELECT * FROM READERS;

CREATE FUNCTION setBestsellerStatus(bookid INT) RETURNS BOOLEAN
BEGIN
    DECLARE RESULT BOOLEAN DEFAULT false;
    DECLARE RENTALS INT DEFAULT 0;
    SELECT COUNT(*) FROM RENTS
    WHERE BOOK_ID = bookid
        INTO RENTALS;

    IF RENTALS >= 2 THEN
        SET RESULT = true;
    ELSE
        SET RESULT = false;
    END IF;
    RETURN RESULT;
END;

DROP PROCEDURE IF EXISTS UpdateBestsellers;
CREATE PROCEDURE UpdateBestsellers()
BEGIN
    DECLARE THIS_BOOK_ID INT;
    DECLARE FINISHED INT DEFAULT 0;
    DECLARE ALL_BOOKS CURSOR FOR SELECT BOOK_ID FROM BOOKS;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
    OPEN ALL_BOOKS;
    WHILE (FINISHED = 0) DO
            FETCH ALL_BOOKS INTO THIS_BOOK_ID;
            IF (FINISHED = 0) THEN
                UPDATE BOOKS SET BESTSELLER = setBestsellerStatus(THIS_BOOK_ID)
                WHERE BOOK_ID = THIS_BOOK_ID;
                COMMIT;
            END IF;
        END WHILE;
    CLOSE ALL_BOOKS;
END;

CALL UpdateBestsellers();