CREATE TABLE STATS(
    STAT_ID INT(11) NOT NULL AUTO_INCREMENT,
    STAT_DATE DATETIME NOT NULL,
    STAT VARCHAR(20) NOT NULL,
    VALUE INT(11) NOT NULL,
    PRIMARY KEY (STAT_ID)
);

CREATE VIEW BESTSELLER_COUNT AS
SELECT COUNT(*) BESTSELLER
    FROM BOOKS
    WHERE BESTSELLER >= 1;

SET @BESTSELLER = 0;

USE kodilla_course;

    CREATE EVENT UPDATE_BESTSELLER_COUNT
    ON SCHEDULE EVERY 10 SECOND
    DO BEGIN
        CALL UpdateBestsellers();

        SELECT * FROM BESTSELLER_COUNT
        INTO @BESTSELLER;

        INSERT INTO STATS(STAT_DATE, STAT, VALUE)
        VALUES(NOW(), "BESTSELLERS", @BESTSELLER);
        COMMIT;
    END;