SELECT IL.NAME, I.SUMMARY
FROM ISSUESLISTS IL
JOIN ISSUES I ON I.ISSUESLIST_ID = IL.ID;

SELECT I.SUMMARY, U.ID
FROM ISSUES I
JOIN USERS U ON I.USER_ID_ASSIGNEDTO = U.ID
ORDER BY I.SUMMARY;

SELECT U.FIRSTNAME, U.LASTNAME, COUNT(*) AS NUMBER_OF_TASKS
FROM USERS U
JOIN ISSUES I ON U.ID = I.USER_ID_ASSIGNEDTO
GROUP BY I.USER_ID_ASSIGNEDTO
HAVING COUNT(*) > 0;
