SELECT * FROM BOOKS;

CREATE TABLE BOOKS_AUD(
    EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
    EVENT_DATE DATETIME NOT NULL,
    EVENT_TYPE VARCHAR(10) DEFAULT NULL,
    BOOK_ID INT (11) NOT NULL,
    OLD_TITLE VARCHAR(255),
    NEW_TITLE VARCHAR(255),
    OLD_PUBYEAR INT(4),
    NEW_PUBYEAR INT(4),
    OLD_BESTSELLER BOOLEAN,
    NEW_BESTSELLER BOOLEAN,
    PRIMARY KEY (EVENT_ID)
);

SELECT * FROM READERS;

CREATE TABLE READERS_AUD(
    EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
    EVENT_DATE DATETIME NOT NULL,
    EVENT_TYPE VARCHAR(10) DEFAULT NULL,
    READERS_ID INT (11) NOT NULL,
    OLD_FIRSTNAME VARCHAR(255),
    NEW_FIRSTNAME VARCHAR(255),
    OLD_LASTNAME VARCHAR(255),
    NEW_LASTNAME VARCHAR(255),
    OLD_PESELID INT(11),
    NEW_PESELID INT(11),
    OLD_VIP_LEVEL VARCHAR(20),
    NEW_VIP_LEVEL VARCHAR(20),
    PRIMARY KEY (EVENT_ID)
);

CREATE TRIGGER BOOKS_INSERT AFTER INSERT ON BOOKS
    FOR EACH ROW
BEGIN
    INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, NEW_TITLE, NEW_PUBYEAR, NEW_BESTSELLER)
    VALUES (CURTIME(), "INSERT", NEW.BOOK_ID, NEW.TITLE, NEW.PUBYEAR, NEW.BESTSELLER);
END;

DROP TRIGGER BOOKS_INSERT;

DROP TABLE BOOKS_AUD;

INSERT INTO BOOKS(TITLE, PUBYEAR)
VALUES ("TESTTITLE", 1990);

UPDATE BOOKS SET TITLE = "TITLE" WHERE BOOK_ID = 19;

DELETE FROM BOOKS WHERE BOOK_ID = 20;

SELECT * FROM BOOKS_AUD;

COMMIT;

CREATE TRIGGER BOOKS_DELETE AFTER DELETE ON BOOKS
FOR EACH ROW
BEGIN
    INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID)
    VALUE (CURTIME(), "DELETE", OLD.BOOK_ID);
END;

CREATE TRIGGER BOOKS_UPDATE AFTER UPDATE ON BOOKS
FOR EACH ROW
BEGIN
    INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, OLD_TITLE,
                           NEW_TITLE, OLD_PUBYEAR, NEW_PUBYEAR, OLD_BESTSELLER, NEW_BESTSELLER)
    VALUE (CURTIME(), "UPDATE", NEW.BOOK_ID, OLD.TITLE, NEW.TITLE,
           OLD.PUBYEAR, NEW.PUBYEAR, OLD.BESTSELLER, NEW.BESTSELLER);
END;

CREATE TRIGGER READERS_UPDATE AFTER UPDATE ON READERS
FOR EACH ROW
BEGIN
    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READERS_ID, OLD_FIRSTNAME,
                NEW_FIRSTNAME, OLD_LASTNAME, NEW_LASTNAME, OLD_PESELID, NEW_PESELID,
                OLD_VIP_LEVEL, NEW_VIP_LEVEL)
    VALUE (CURTIME(), "UPDATE", OLD.READERS_ID, OLD.FIRSTNAME,
                NEW.FIRSTNAME, OLD.LASTNAME, NEW.LASTNAME, OLD.PESELID, NEW.PESELID,
                OLD.VIP_LEVEL, NEW.VIP_LEVEL);
END;

CREATE TRIGGER READERS_INSERT AFTER INSERT ON READERS
FOR EACH ROW
BEGIN
    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READERS_ID,
                NEW_FIRSTNAME, NEW_LASTNAME, NEW_PESELID, NEW_VIP_LEVEL)
    VALUE (CURTIME(), "INSERT", NEW.READERS_ID, NEW.FIRSTNAME, NEW.LASTNAME,
            NEW.PESELID, NEW.VIP_LEVEL);
END;

INSERT INTO READERS(FIRSTNAME, LASTNAME, PESELID)
VALUES("PIXEL", "FORD", 12345);

COMMIT;

CREATE TRIGGER READERS_DELETE AFTER DELETE ON READERS
FOR EACH ROW
BEGIN
    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READERS_ID)
    VALUE (CURTIME(), "DELETE", OLD.READERS_ID);
END;